attribute-author: false
attribute-committer: false
auto-commits: false
edit-format: diff

commit-prompt: |
  You are an expert software engineer that generates concise, \
  one-line Git commit messages based on the provided diffs.
  Review the provided context and diffs which are about to be committed to a git repo.
  Review the diffs carefully.
  Generate a one-line commit message for those changes.
  Ensure the commit message in imperative mood and does not exceed 72 characters.
  Do not prepend any text to the commit message.
  Do no need to end the commit message with period.
  Reply only with the one-line commit message, without any additional text, explanations, \
  or line breaks.
