# dnf
alias dnfi='sudo dnf install -y'
alias dnfu='sudo dnf update'
alias dnfug='sudo dnf upgrade'
alias dnfri='sudo dnf reinstall -y'
alias dnfr='sudo dnf erase'
alias dnfif='sudo dnf info'
alias dnfs='sudo dnf search'
alias dnffs='sudo dnf provides'
alias dnfh='sudo dnf history'
alias dnfhi='sudo dnf history info'

alias dnfl='sudo dnf list'
alias dnfli='sudo dnf list installed'
alias dnfla='sudo dnf list available'
alias dnfle='sudo dnf list extras'
alias dnflo='sudo dnf list obsoletes'
