#!/bin/bash
# This hook is run after every virtualenv is activated.

# via http://virtualenvwrapper.readthedocs.org/en/latest/tips.html#creating-project-work-directories
proj_name=$(basename $VIRTUAL_ENV)
cd $PROJECT_HOME/$proj_name
